version: '3.8'

services:
  certification:
    build: ./certification
    env_file:
      - ./env/.env.domain
    volumes:
      - type: volume 
        source: ssl-certificates
        target: /etc/letsencrypt
      - type: volume
        source: certbot-challenges
        target: /var/www/certbot
  proxy:
    build: ./proxy
    env_file:
      - ./env/.env.domain
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: ssl-certificates
        target: /etc/letsencrypt
      - type: volume
        source: certbot-challenges
        target: /var/www/certbot
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    env_file:
      - ./env/.env.domain
      - ./env/.env.stripe
    depends_on:
      - backend
  backend:
    build: ./backend
    env_file:
      - ./env/.env.domain
      - ./env/.env.stripe
      - ./env/.env.backend
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db
    ports:
      - 27017:27017

volumes:
  mongodb-data:
  ssl-certificates:
  certbot-challenges: