version: '3.8'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.domain
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
  database:
    image: mongo
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db

volumes:
  mongodb-data:
  ssl-certificates:
  certbot-challenges: