version: '3.8'

services:
  certification:
    build: ./certification
    env_file:
      - ./.env.domain
    volumes:
      - type: volume 
        source: ssl-certificates
        target: /etc/letsencrypt
      - type: volume
        source: certbot-challenges
        target: /var/www/certbot
  proxy:
    build: ./proxy
    env_file:
      - ./.env.domain
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: ssl-certificates
        target: /etc/letsencrypt
      - type: volume
        source: certbot-challenges
        target: /var/www/certbot
  frontend:
    build: ./frontend
    depends_on:
      - backend
  backend:
    build: ./backend
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db

volumes:
  mongodb-data:
  ssl-certificates:
  certbot-challenges: