FROM nginx:1.19.2-alpine

RUN apk add inotify-tools openssl

COPY dev.conf /etc/nginx/conf.d/default.conf

COPY options-ssl-nginx.conf /etc/nginx/options-ssl-nginx.conf

COPY entrypoint.sh entrypoint.sh

CMD ["sh", "entrypoint.sh"]
